// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yggszjurxladclvbolra.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlnZ3N6anVyeGxhZGNsdmJvbHJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0ODcyNTcsImV4cCI6MjA3MDA2MzI1N30.aCOFkYd_KkdPGgStVjGQ6kCjC_yeI32_XDIbmh6PbFY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});